// Demo seed data for the 1st update (auth users + homepage feed).
// All seeded users share the password:  password123

export const SEED_PASSWORD = 'password123';

export const seedUsers = [
  {
    id: 'lead-1',
    firstName: 'Rahat',
    lastName: 'Ahmed',
    name: 'Rahat Ahmed',
    handle: '@rahatahmed',
    email: 'rahat.ahmed@example.com',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&auto=format&fit=crop&q=80',
    role: 'creator',
    category: 'Singing',
    location: 'Dhaka, Bangladesh',
    bio: 'Singer and performer.',
    talentCount: 14,
    score: 1200,
    likes: 125400,
    votes: 1200,
    rank: 1,
  },
  {
    id: 'lead-2',
    firstName: 'Subarna',
    lastName: 'Khan',
    name: 'Subarna Khan',
    handle: '@subarnakhan',
    email: 'subarna.khan@example.com',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80',
    role: 'creator',
    category: 'Others / Filmmaking',
    location: 'Rajshahi, Bangladesh',
    bio: 'Filmmaker and storyteller.',
    talentCount: 8,
    score: 950,
    likes: 98000,
    votes: 950,
    rank: 2,
  },
  {
    id: 'lead-3',
    firstName: 'Arfan',
    lastName: 'Nisho',
    name: 'Arfan Nisho',
    handle: '@afrannisho',
    email: 'arfan.nisho@example.com',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&auto=format&fit=crop&q=80',
    role: 'creator',
    category: 'Dancing',
    location: 'Dhaka, Bangladesh',
    bio: 'Dancer and choreographer.',
    talentCount: 11,
    score: 870,
    likes: 85200,
    votes: 870,
    rank: 3,
  },
  {
    id: 'lead-4',
    firstName: 'Khaled',
    lastName: 'Hasan',
    name: 'Khaled Hasan',
    handle: '@khaledhasanmilu',
    email: 'khaled.hasan@example.com',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    role: 'creator',
    category: 'Art & Vocal',
    location: 'Dhaka, Bangladesh',
    bio: 'Dreamer | Performer | Believer. I love to sing and capture moments.',
    talentCount: 10,
    score: 790,
    likes: 67400,
    votes: 790,
    rank: 4,
  },
  {
    id: 'lead-5',
    firstName: 'Redwanul',
    lastName: 'Karim',
    name: 'Redwanul Karim',
    handle: '@redwanul_dev',
    email: 'redwanul@example.com',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    role: 'creator',
    category: 'Instrumental',
    location: 'Dhaka, Bangladesh',
    bio: 'Instrumentalist.',
    talentCount: 6,
    score: 710,
    likes: 54000,
    votes: 710,
    rank: 5,
  },
  {
    id: 'lead-6',
    firstName: 'Minhazul',
    lastName: 'Islam',
    name: 'Minhazul',
    handle: '@minhazul_official',
    email: 'minhazul@example.com',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80',
    role: 'creator',
    category: '3D Art',
    location: 'Chittagong, Bangladesh',
    bio: '3D and motion artist.',
    talentCount: 7,
    score: 650,
    likes: 49000,
    votes: 650,
    rank: 6,
  },
  {
    id: 'lead-7',
    firstName: 'Nurul',
    lastName: 'Huda',
    name: 'Nurul Huda',
    handle: '@nurulhuda',
    email: 'nurul.huda@example.com',
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&auto=format&fit=crop&q=80',
    role: 'creator',
    category: 'Poetry',
    location: 'Sylhet, Bangladesh',
    bio: 'Poet and writer.',
    talentCount: 9,
    score: 540,
    likes: 38000,
    votes: 540,
    rank: 7,
  },
  {
    id: 'lead-8',
    firstName: 'Mahi',
    lastName: 'Islam',
    name: 'Mahi Islam',
    handle: '@mahiislam',
    email: 'mahi.islam@example.com',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
    role: 'creator',
    category: 'Singing',
    location: 'Dhaka, Bangladesh',
    bio: 'Singer.',
    talentCount: 5,
    score: 430,
    likes: 29000,
    votes: 430,
    rank: 8,
  },
];

export const seedTalents = [
  {
    id: 'talent-1',
    title: 'Soulful Vibes',
    type: 'video',
    category: 'Singing',
    authorName: 'Rahat Ahmed',
    authorHandle: '@rahatahmed',
    authorAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&auto=format&fit=crop&q=80',
    authorLocation: 'Dhaka, Bangladesh',
    authorRank: 12,
    isVerified: 1,
    createdLabel: 'Jul 25, 2026',
    likes: 125400,
    views: 500200,
    commentsCount: 1540,
    votes: 125000,
    description: 'Just a little try to express my feeling through this song. Hope you all like it and support my journey in music!',
    thumbnail: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&auto=format&fit=crop&q=80',
    contentUrl: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/friday.mp4',
    poemText: null,
    audioDuration: null,
    tags: ['Acoustic', 'Vocal', 'LivePerformance', 'Original'],
    audioWaveform: null,
  },
  {
    id: 'talent-2',
    title: 'আগামীর সময় (Upcoming Time)',
    type: 'text',
    category: 'Poetry',
    authorName: 'Hasan Mahmud',
    authorHandle: '@hasanmahmud',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    authorLocation: 'Chittagong, Bangladesh',
    authorRank: 2,
    isVerified: 1,
    createdLabel: 'Jul 25, 2026',
    likes: 16800,
    views: 15400,
    commentsCount: 5200,
    votes: 15900,
    description: 'A poetic ode to resilience, dreams, and the dawn of a new generation.',
    thumbnail: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&auto=format&fit=crop&q=80',
    contentUrl: null,
    poemText: [
      'সত্যের আলোক জ্বেলে, কাটে কালো ভয়,',
      'তটিনীর ধারা বেয়ে, এলো যে সময়।',
      'অপপ্রচারের বাণে, তুমি শক্ত বাঁধ,',
      'নিশার আঁধার চিরে, আনো পূর্ণ চাঁদ।',
      '',
      'সকল বীরের কথা, পাতায় পাতায়,',
      'তোমার সাহসে আজ, মুক্তি খুঁজে পায়।',
      'দায়িত্ব পালনে তুমি, রবে অবিচল,',
      'তোমারি আলোতে হাসে, সুদিন উজ্জ্বল।',
      '',
      'নতুনের জয়গান, গাছে এ মাতৃক,',
      'আঁধারে জ্বালিয়ে দিলে, আশার বর্তিক।',
      'বীরদের এই বাণী, ছড়ালো সুবাস,',
      'জাগালো সবার মনে, সুদৃঢ় বিশ্বাস।',
      '',
      'সময়ের দাবি মেনে, চলুক এ তরী,',
      '‘আগামীর সময়’ কে, ধন্য মোরা করি।',
    ],
    audioDuration: null,
    tags: ['BengaliPoetry', 'Inspiration', 'Literature', 'Rhymes'],
    audioWaveform: null,
  },
  {
    id: 'talent-3',
    title: 'Voice of Nirob',
    type: 'audio',
    category: 'Singing',
    authorName: 'Nirob Hossen',
    authorHandle: '@nirobhossen',
    authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    authorLocation: 'Sylhet, Bangladesh',
    authorRank: 10,
    isVerified: 1,
    createdLabel: 'Jul 25, 2026',
    likes: 125000,
    views: 125000,
    commentsCount: 125000,
    votes: 125000,
    description: 'An ethereal instrumental vocal performance blending soft eastern melodies with modern ambient soundscapes.',
    thumbnail: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&auto=format&fit=crop&q=80',
    contentUrl: 'https://actions.google.com/sounds/v1/ambiences/outdoor_ambience.ogg',
    poemText: null,
    audioDuration: '4:47',
    tags: ['AudioShowcase', 'AcousticSoul', 'IndieMusic', 'Melody'],
    audioWaveform: [24, 42, 68, 85, 45, 30, 72, 90, 60, 48, 80, 95, 70, 55, 35, 65, 88, 76, 54, 92, 100, 65, 40, 78, 85, 60, 30, 45, 65, 80, 95, 70, 50, 60, 75, 90, 82, 45, 30, 20],
  },
  {
    id: 'talent-4',
    title: 'Melody of Life',
    type: 'video',
    category: 'Singing',
    authorName: 'Riya Hasan',
    authorHandle: '@riyahasan',
    authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop&q=80',
    authorLocation: 'Dhaka, Bangladesh',
    authorRank: 8,
    isVerified: 1,
    createdLabel: 'Aug 10, 2026',
    likes: 25400,
    views: 150000,
    commentsCount: 980,
    votes: 24100,
    description: 'A tribute cover celebrating life and harmonic balance.',
    thumbnail: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=800&auto=format&fit=crop&q=80',
    contentUrl: 'https://download.samplelib.com/mp4/sample-10s.mp4',
    poemText: null,
    audioDuration: null,
    tags: ['Music', 'Vocal', 'Cover'],
    audioWaveform: null,
  },
  {
    id: 'talent-5',
    title: 'Street Dancer',
    type: 'video',
    category: 'Dancing',
    authorName: 'Afran Nisho',
    authorHandle: '@afrannisho',
    authorAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&auto=format&fit=crop&q=80',
    authorLocation: 'Dhaka, Bangladesh',
    authorRank: 3,
    isVerified: 1,
    createdLabel: 'Aug 14, 2026',
    likes: 20500,
    views: 140000,
    commentsCount: 1120,
    votes: 19800,
    description: 'Urban popping and locking street choreography recorded at sunset.',
    thumbnail: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800&auto=format&fit=crop&q=80',
    contentUrl: 'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/720/Big_Buck_Bunny_720_10s_1MB.mp4',
    poemText: null,
    audioDuration: null,
    tags: ['HipHop', 'Dance', 'StreetStyle', 'Urban'],
    audioWaveform: null,
  },
  {
    id: 'talent-6',
    title: 'Colors of Nature',
    type: 'video',
    category: 'Art',
    authorName: 'Khaled Hasan Milu',
    authorHandle: '@khaledhasanmilu',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    authorLocation: 'Dhaka, Bangladesh',
    authorRank: 4,
    isVerified: 1,
    createdLabel: 'Aug 18, 2026',
    likes: 202,
    views: 1040,
    commentsCount: 45,
    votes: 790,
    description: 'Acrylic canvas painting timelapse capturing golden sunset over green mountain meadows.',
    thumbnail: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800&auto=format&fit=crop&q=80',
    contentUrl: 'https://media.w3.org/2010/05/sintel/trailer.mp4',
    poemText: null,
    audioDuration: null,
    tags: ['FineArt', 'NaturePainting', 'Acrylic', 'Timelapse'],
    audioWaveform: null,
  },
  {
    id: 'talent-7',
    title: 'How to create a video',
    type: 'video',
    category: 'Others',
    authorName: 'Subarna Khan',
    authorHandle: '@subarnakhan',
    authorAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80',
    authorLocation: 'Rajshahi, Bangladesh',
    authorRank: 2,
    isVerified: 1,
    createdLabel: 'Aug 22, 2026',
    likes: 40000,
    views: 230000,
    commentsCount: 3100,
    votes: 38200,
    description: 'Masterclass on cinematography, composition, and storytelling on a minimal budget.',
    thumbnail: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800&auto=format&fit=crop&q=80',
    contentUrl: 'https://filesamples.com/samples/video/mp4/sample_640x360.mp4',
    poemText: null,
    audioDuration: null,
    tags: ['Filmmaking', 'Tutorial', 'Cinematography'],
    audioWaveform: null,
  },
  {
    id: 'talent-8',
    title: 'Life is Good',
    type: 'video',
    category: 'Art',
    authorName: 'Minhazul',
    authorHandle: '@minhazul_official',
    authorAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80',
    authorLocation: 'Dhaka, Bangladesh',
    authorRank: 6,
    isVerified: 1,
    createdLabel: 'Aug 25, 2026',
    likes: 25000,
    views: 150000,
    commentsCount: 890,
    votes: 24500,
    description: 'Digital 3D motion design & optical lighting synthesis.',
    thumbnail: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=800&auto=format&fit=crop&q=80',
    contentUrl: 'https://download.samplelib.com/mp4/sample-20s.mp4',
    poemText: null,
    audioDuration: null,
    tags: ['3DArt', 'Motion', 'VFX'],
    audioWaveform: null,
  },
  {
    id: 'talent-9',
    title: 'Dance Fire',
    type: 'video',
    category: 'Dancing',
    authorName: 'Tasmire Haque',
    authorHandle: '@tasmirehaque',
    authorAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
    authorLocation: 'Khulna, Bangladesh',
    authorRank: 7,
    isVerified: 0,
    createdLabel: 'Aug 28, 2026',
    likes: 120000,
    views: 620000,
    commentsCount: 4200,
    votes: 118000,
    description: 'High tempo contemporary fire choreography.',
    thumbnail: 'https://images.unsplash.com/photo-1547153760-18fc86324498?w=800&auto=format&fit=crop&q=80',
    contentUrl: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/friday.mp4',
    poemText: null,
    audioDuration: null,
    tags: ['Contemporary', 'DanceEnergy', 'Stage'],
    audioWaveform: null,
  },
  {
    id: 'talent-10',
    title: 'Voice of Soul',
    type: 'audio',
    category: 'Singing',
    authorName: 'Afrin Tashu',
    authorHandle: '@afrintashu',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    authorLocation: 'Dhaka, Bangladesh',
    authorRank: 5,
    isVerified: 1,
    createdLabel: 'Aug 29, 2026',
    likes: 150000,
    views: 740000,
    commentsCount: 9200,
    votes: 148000,
    description: 'A soothing classical vocal rendition with acoustic guitar accompaniment.',
    thumbnail: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop&q=80',
    contentUrl: null,
    poemText: null,
    audioDuration: '3:52',
    tags: ['Soul', 'Classical', 'Vocalist'],
    audioWaveform: [30, 45, 60, 75, 90, 65, 45, 55, 70, 85, 90, 60, 40, 50, 70, 85, 95, 65, 40, 30, 50, 75, 90, 80, 55, 45, 60, 80, 95, 70, 50, 40, 60, 75, 90, 65, 45, 30, 20, 15],
  },
  {
    id: 'talent-11',
    title: 'Life in Colors',
    type: 'video',
    category: 'Art',
    authorName: 'Sakib Uddin',
    authorHandle: '@sakibuddin',
    authorAvatar: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=400&auto=format&fit=crop&q=80',
    authorLocation: 'Dhaka, Bangladesh',
    authorRank: 1,
    isVerified: 1,
    createdLabel: 'Aug 30, 2026',
    likes: 10000000,
    views: 24000000,
    commentsCount: 145000,
    votes: 9800000,
    description: 'A global art mural painted across a 50ft canvas depicting human connection.',
    thumbnail: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800&auto=format&fit=crop&q=80',
    contentUrl: 'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/720/Big_Buck_Bunny_720_10s_1MB.mp4',
    poemText: null,
    audioDuration: null,
    tags: ['Mural', 'GlobalArt', 'Painting'],
    audioWaveform: null,
  },
];
